[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[line_break]
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = "[](orange)"
symbols.Windows = "[](blue)"