command_timeout=10000
add_newline=true

[aws]
symbol = "  "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 6
truncate_to_repo = true

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os]
disabled = false

[os.symbols]
Ubuntu = "[ ](orange)"
Windows = "[󰍲 ](blue)"
Unknown = " "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[username]
disabled = true
